/**
 * useAIInsights — fetches structured insight cards from the backend AI service.
 */

import React, { useState, useEffect } from 'react';
import { aiService } from '../services/hrmsApi';
import type { HrSummary } from '../services/hrmsApi';

// Re-export AIInsight from hrmsApi to avoid breaking existing consumers
export type { AIInsight } from '../services/hrmsApi';
import type { AIInsight } from '../services/hrmsApi';

export interface UseAIInsightsReturn {
  insights: AIInsight[];
  loading: boolean;
  streaming: boolean;
  error: string | null;
  streamingText: string;
  generate: () => void;
  lastGeneratedAt: Date | null;
}

export function useAIInsights(summary: HrSummary | null): UseAIInsightsReturn {
  const [insights, setInsights] = useState<AIInsight[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [lastGeneratedAt, setLastGeneratedAt] = useState<Date | null>(null);

  async function generate() {
    if (loading) return;
    setLoading(true);
    setError(null);

    try {
      // Send the structured data to the backend. The backend owns prompt construction.
      const payload = summary ? { summary } : {};
      const res = await aiService.getInsights(payload);

      if (res.success && res.insights) {
        setInsights(res.insights);
        setLastGeneratedAt(new Date());
      } else {
        throw new Error('Backend failed to return insights');
      }
    } catch (err) {
      setError(
        err instanceof Error ? err.message : 'Failed to generate insights'
      );
    } finally {
      setLoading(false);
    }
  }

  // Auto-generate when summary first becomes available
  // Uses a ref to ensure we only trigger once even if summary changes later
  const hasAutoGenerated = React.useRef(false);
  useEffect(() => {
    if (summary && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      const timer = setTimeout(() => void generate(), 800);
      return () => clearTimeout(timer);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [summary]);

  return {
    insights,
    loading,
    streaming: false, // Kept for interface compatibility, unsupported by new endpoint yet
    error,
    streamingText: '', // Kept for interface compatibility
    generate,
    lastGeneratedAt,
  };
}
