import { useState, useMemo } from 'react';
import { ChevronDown, Search, Mail, Clock, MessageCircle } from 'lucide-react';
import DashboardLayout from '../layouts/DashboardLayout';

// ─── FAQ Data ────────────────────────────────────────────────────────────────

interface FAQItem {
  id: string;
  question: string;
  answer: string;
}

interface FAQCategory {
  id: string;
  label: string;
  icon: string;
  items: FAQItem[];
}

const FAQ_CATEGORIES: FAQCategory[] = [
  {
    id: 'getting-started',
    label: 'Getting Started',
    icon: '🚀',
    items: [
      {
        id: 'gs-1',
        question: 'How do I log in to HRMSPro?',
        answer:
          'Visit the login page and enter your registered work email and password. If you\'ve forgotten your password, click "Forgot Password" to receive a reset link. First-time users will receive a temporary password via email from your HR team.',
      },
      {
        id: 'gs-2',
        question: 'What is the difference between the Employee and HR Manager dashboards?',
        answer:
          'The Employee dashboard shows your personal data — attendance, your leave requests, your payslips, and your documents. The HR Manager dashboard provides company-wide visibility: all employees\' attendance, the leave approval queue, payroll management, and workforce analytics.',
      },
      {
        id: 'gs-3',
        question: 'How do I update my profile information?',
        answer:
          'Click your avatar in the top-right navbar, select "My Profile", and edit your contact details, emergency contacts, and bank account information. Changes to core details like your name or employee ID must be submitted via a request to HR.',
      },
      {
        id: 'gs-4',
        question: 'Can I use HRMSPro on my mobile device?',
        answer:
          'Yes. HRMSPro is fully responsive and works on all modern browsers on smartphones and tablets. A dedicated mobile app is on the product roadmap for a future release.',
      },
    ],
  },
  {
    id: 'leave-attendance',
    label: 'Leave & Attendance',
    icon: '📅',
    items: [
      {
        id: 'la-1',
        question: 'How do I apply for leave?',
        answer:
          'Navigate to the Leave page from the sidebar. Under the "Apply for Leave" form, select your leave type (Casual, Sick, Earned, etc.), choose start and end dates, enter a reason, and click Submit. Your request will appear in the HR approval queue automatically.',
      },
      {
        id: 'la-2',
        question: 'How long does it take for a leave request to be approved?',
        answer:
          'Approval timelines depend on your HR team\'s process. You will receive a notification inside the app as soon as your request is approved or rejected. Typical response time is 1–2 business days.',
      },
      {
        id: 'la-3',
        question: 'What happens if I check in late?',
        answer:
          'A late check-in (after the configured grace period) will be flagged in the Attendance page and marked as "Late". You will receive a notification prompting you to add a remark explaining the reason. Repeated late check-ins may be escalated to your manager.',
      },
      {
        id: 'la-4',
        question: 'Can I cancel a leave request after submitting it?',
        answer:
          'Leave cancellation before approval can be done directly from your leave history table. Once approved, you must contact HR to cancel — a cancellation request will be sent for their review.',
      },
      {
        id: 'la-5',
        question: 'How do I check my remaining leave balance?',
        answer:
          'Your leave balance is visible on the Leave page summary cards. The three cards show Pending, Approved, and Rejected counts for the current period. Full quota details are available under Settings → Leave Balance.',
      },
    ],
  },
  {
    id: 'payroll-payslips',
    label: 'Payroll & Payslips',
    icon: '💰',
    items: [
      {
        id: 'pp-1',
        question: 'When are payslips generated?',
        answer:
          'Payslips are generated by your HR team after monthly payroll is processed — typically in the first week of the following month. You will receive an in-app notification as soon as your payslip is ready.',
      },
      {
        id: 'pp-2',
        question: 'How do I download my payslip?',
        answer:
          'Go to Payroll → My Payslips. Find the month you need and click the "Download" button in the Action column. A print dialog will open where you can save the payslip as a PDF to your device.',
      },
      {
        id: 'pp-3',
        question: 'My payslip figures look incorrect. What should I do?',
        answer:
          'First, verify your gross pay, deductions (TDS, PF, Other), and net pay on the payslip. If there is a discrepancy, contact your HR Manager directly with the specific figures in question. Do not make assumptions — salary errors must be resolved before the next payroll cycle.',
      },
      {
        id: 'pp-4',
        question: 'What deductions appear on my payslip?',
        answer:
          'Standard deductions include Income Tax (TDS), Employee Provident Fund (EPF/PF), and any other applicable statutory or voluntary deductions. The exact breakdown is itemized on every payslip download.',
      },
    ],
  },
  {
    id: 'account-security',
    label: 'Account & Security',
    icon: '🔐',
    items: [
      {
        id: 'as-1',
        question: 'How do I change my password?',
        answer:
          'Go to Settings → Security and click "Change Password". Enter your current password, followed by your new password twice. Passwords must be at least 8 characters and include a mix of letters, numbers, and symbols.',
      },
      {
        id: 'as-2',
        question: 'What should I do if I suspect unauthorized access to my account?',
        answer:
          'Change your password immediately via Settings → Security. Then contact your HR Administrator or IT support to report the incident. They can review access logs and revoke any active sessions on your behalf.',
      },
      {
        id: 'as-3',
        question: 'Is my payroll and personal data encrypted?',
        answer:
          'Yes. All data in HRMSPro is encrypted in transit (TLS) and at rest. Payroll data is additionally access-controlled — employees can only view their own records, and HR Managers have scoped access based on their organizational permissions.',
      },
      {
        id: 'as-4',
        question: 'How do I log out securely?',
        answer:
          'Click your avatar in the top-right navbar and select "Logout". This clears your session token from the browser. For shared or public devices, always log out explicitly and close the browser tab afterward.',
      },
    ],
  },
];

// ─── Accordion Item ───────────────────────────────────────────────────────────

function AccordionItem({ item, isOpen, onToggle }: {
  item: FAQItem;
  isOpen: boolean;
  onToggle: () => void;
}) {
  return (
    <div className={`border-b border-slate-100 last:border-0 dark:border-white/5`}>
      <button
        type="button"
        onClick={onToggle}
        className="flex w-full items-start justify-between gap-4 px-5 py-4 text-left transition-colors hover:bg-slate-50 dark:hover:bg-white/[0.03]"
      >
        <span className={`text-sm font-semibold leading-snug transition-colors ${isOpen ? 'text-blue-600 dark:text-blue-400' : 'text-slate-800 dark:text-slate-200'}`}>
          {item.question}
        </span>
        <span className={`mt-0.5 shrink-0 text-slate-400 transition-transform duration-200 ${isOpen ? 'rotate-180 text-blue-500' : ''}`}>
          <ChevronDown className="h-4 w-4" />
        </span>
      </button>
      {isOpen && (
        <div className="px-5 pb-4">
          <p className="text-sm leading-relaxed text-slate-600 dark:text-slate-400">
            {item.answer}
          </p>
        </div>
      )}
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function HelpCenterPage() {
  const [search, setSearch] = useState('');
  const [openId, setOpenId] = useState<string | null>(null);

  // Search: flatten all items across categories and filter
  const searchResults = useMemo(() => {
    if (!search.trim()) return null;
    const q = search.toLowerCase();
    return FAQ_CATEGORIES.flatMap((cat) =>
      cat.items
        .filter((item) =>
          item.question.toLowerCase().includes(q) || item.answer.toLowerCase().includes(q)
        )
        .map((item) => ({ ...item, categoryLabel: cat.label, categoryIcon: cat.icon }))
    );
  }, [search]);

  const toggle = (id: string) => setOpenId((prev) => (prev === id ? null : id));

  return (
    <DashboardLayout title="Help Center">
      {/* Ambient glows — dark mode only */}
      <div className="pointer-events-none fixed inset-0 z-0 overflow-hidden hidden dark:block">
        <div className="absolute -right-[15%] -top-[10%] h-[55vw] w-[55vw] rounded-full bg-blue-600/8 blur-[140px]" />
        <div className="absolute left-[25%] top-[35%] h-[35vw] w-[35vw] rounded-full bg-indigo-600/5 blur-[100px]" />
      </div>

      <div className="relative z-10 space-y-5">

        {/* ── Header + Search ── */}
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h1 className="text-xl font-extrabold tracking-tight text-slate-900 dark:text-white">Help Center</h1>
            <p className="mt-0.5 text-sm text-slate-500 dark:text-slate-400">
              Find answers to common questions about HRMSPro.
            </p>
          </div>
        </div>

        {/* Search bar */}
        <div className="relative">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
          <input
            type="text"
            placeholder="Search questions..."
            value={search}
            onChange={(e) => { setSearch(e.target.value); setOpenId(null); }}
            className="w-full rounded-2xl border border-slate-200 bg-white py-3 pl-11 pr-4 text-sm text-slate-700 shadow-sm outline-none placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10 dark:border-white/10 dark:bg-[#0B1121] dark:text-white dark:placeholder:text-slate-500 dark:focus:border-blue-500/50"
          />
        </div>

        {/* ── Search Results ── */}
        {searchResults !== null ? (
          <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-[#0B1121] dark:shadow-xl">
            <div className="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-white/10">
              <h2 className="font-bold text-slate-950 dark:text-white">Search Results</h2>
              <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-600 dark:bg-blue-500/20 dark:text-blue-400">
                {searchResults.length} result{searchResults.length !== 1 ? 's' : ''}
              </span>
            </div>
            {searchResults.length === 0 ? (
              <div className="px-5 py-10 text-center">
                <p className="text-sm text-slate-500 dark:text-slate-400">No questions matched "<span className="font-semibold">{search}</span>". Try different keywords or browse the categories below.</p>
              </div>
            ) : (
              searchResults.map((item) => (
                <div key={item.id}>
                  <div className="border-b border-slate-100 px-5 pt-3 pb-1 dark:border-white/5">
                    <span className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400 dark:text-slate-500">
                      {item.categoryIcon} {item.categoryLabel}
                    </span>
                  </div>
                  <AccordionItem
                    item={item}
                    isOpen={openId === item.id}
                    onToggle={() => toggle(item.id)}
                  />
                </div>
              ))
            )}
          </div>
        ) : (
          /* ── FAQ Categories ── */
          <div className="space-y-4">
            {FAQ_CATEGORIES.map((cat) => (
              <div
                key={cat.id}
                className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-[#0B1121] dark:shadow-xl"
              >
                {/* Category header */}
                <div className="flex items-center gap-3 border-b border-slate-200 px-5 py-4 dark:border-white/10">
                  <span className="text-lg">{cat.icon}</span>
                  <h2 className="font-bold text-slate-950 dark:text-white">{cat.label}</h2>
                  <span className="ml-auto rounded-full bg-slate-100 px-2.5 py-0.5 text-[11px] font-bold text-slate-500 dark:bg-white/5 dark:text-slate-400">
                    {cat.items.length} questions
                  </span>
                </div>

                {/* FAQ items */}
                {cat.items.map((item) => (
                  <AccordionItem
                    key={item.id}
                    item={item}
                    isOpen={openId === item.id}
                    onToggle={() => toggle(item.id)}
                  />
                ))}
              </div>
            ))}
          </div>
        )}

        {/* ── Contact Support Card ── */}
        <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-[#0B1121] dark:shadow-xl">
          <div className="border-b border-slate-200 px-5 py-4 dark:border-white/10">
            <h2 className="font-bold text-slate-950 dark:text-white">Still need help?</h2>
            <p className="mt-0.5 text-sm text-slate-500 dark:text-slate-400">
              Can't find what you're looking for? Reach out to our support team.
            </p>
          </div>
          <div className="grid gap-0 sm:grid-cols-3">
            {[
              {
                icon: <Mail className="h-5 w-5" />,
                label: 'Email Support',
                value: 'hr-support@hrmspro.in',
                sub: 'We reply within 1 business day',
                color: 'text-blue-500 bg-blue-50 dark:bg-blue-500/20',
              },
              {
                icon: <Clock className="h-5 w-5" />,
                label: 'Support Hours',
                value: 'Mon – Fri, 9 AM – 6 PM',
                sub: 'IST (India Standard Time)',
                color: 'text-emerald-500 bg-emerald-50 dark:bg-emerald-500/20',
              },
              {
                icon: <MessageCircle className="h-5 w-5" />,
                label: 'Internal Helpdesk',
                value: 'helpdesk.hrmspro.in',
                sub: 'Raise a ticket for IT or HR issues',
                color: 'text-violet-500 bg-violet-50 dark:bg-violet-500/20',
              },
            ].map((card, i) => (
              <div
                key={card.label}
                className={`flex items-start gap-4 p-5 ${i < 2 ? 'border-b border-slate-100 dark:border-white/5 sm:border-b-0 sm:border-r' : ''}`}
              >
                <span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${card.color}`}>
                  {card.icon}
                </span>
                <div className="min-w-0">
                  <p className="text-[11px] font-extrabold uppercase tracking-wider text-slate-400 dark:text-slate-500">{card.label}</p>
                  <p className="mt-0.5 text-sm font-bold text-slate-900 dark:text-white truncate">{card.value}</p>
                  <p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{card.sub}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </DashboardLayout>
  );
}
