import FAQCategory from '../models/FAQCategory.js';

export const getFAQs = async (req, res) => {
  try {
    const categories = await FAQCategory.find();
    res.status(200).json({ success: true, categories });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch FAQs', error: error.message });
  }
};

export const seedFAQs = async (req, res) => {
  try {
    // Restrict seeding to HR Managers or Admin
    let userRole = (req.user?.role || "").toLowerCase();
    if (userRole === "hr") userRole = "hr-manager";
    if (userRole !== 'hr-manager' && userRole !== 'admin') {
      return res.status(403).json({ success: false, message: 'Unauthorized' });
    }
    
    await FAQCategory.deleteMany({});
    
    const seedData = [
      {
        id: 'getting-started',
        label: 'Getting Started',
        icon: 'Rocket',
        items: [
          {
            id: 'gs-1',
            question: 'How do I log in to HRMSPro?',
            answer: 'Visit the login page and enter your registered work email and password. If you\'ve forgotten your password, click "Forgot Password" to receive a reset link. First-time users will receive a temporary password via email from your HR team.',
          },
          {
            id: 'gs-2',
            question: 'What is the difference between the Employee and HR Manager dashboards?',
            answer: 'The Employee dashboard shows your personal data — attendance, your leave requests, your payslips, and your documents. The HR Manager dashboard provides company-wide visibility: all employees\' attendance, the leave approval queue, payroll management, and workforce analytics.',
          },
          {
            id: 'gs-3',
            question: 'How do I update my profile information?',
            answer: 'Click your avatar in the top-right navbar, select "My Profile", and edit your contact details, emergency contacts, and bank account information. Changes to core details like your name or employee ID must be submitted via a request to HR.',
          },
          {
            id: 'gs-4',
            question: 'Can I use HRMSPro on my mobile device?',
            answer: 'Yes. HRMSPro is fully responsive and works on all modern browsers on smartphones and tablets. A dedicated mobile app is on the product roadmap for a future release.',
          },
        ],
      },
      {
        id: 'leave-attendance',
        label: 'Leave & Attendance',
        icon: 'Calendar',
        items: [
          {
            id: 'la-1',
            question: 'How do I apply for leave?',
            answer: 'Navigate to the Leave page from the sidebar. Under the "Apply for Leave" form, select your leave type (Casual, Sick, Earned, etc.), choose start and end dates, enter a reason, and click Submit. Your request will appear in the HR approval queue automatically.',
          },
          {
            id: 'la-2',
            question: 'How long does it take for a leave request to be approved?',
            answer: 'Approval timelines depend on your HR team\'s process. You will receive a notification inside the app as soon as your request is approved or rejected. Typical response time is 1–2 business days.',
          },
          {
            id: 'la-3',
            question: 'What happens if I check in late?',
            answer: 'A late check-in (after the configured grace period) will be flagged in the Attendance page and marked as "Late". You will receive a notification prompting you to add a remark explaining the reason. Repeated late check-ins may be escalated to your manager.',
          },
          {
            id: 'la-4',
            question: 'Can I cancel a leave request after submitting it?',
            answer: 'Leave cancellation before approval can be done directly from your leave history table. Once approved, you must contact HR to cancel — a cancellation request will be sent for their review.',
          },
          {
            id: 'la-5',
            question: 'How do I check my remaining leave balance?',
            answer: 'Your leave balance is visible on the Leave page summary cards. The three cards show Pending, Approved, and Rejected counts for the current period. Full quota details are available under Settings → Leave Balance.',
          },
        ],
      },
      {
        id: 'payroll-payslips',
        label: 'Payroll & Payslips',
        icon: 'Coins',
        items: [
          {
            id: 'pp-1',
            question: 'When are payslips generated?',
            answer: 'Payslips are generated by your HR team after monthly payroll is processed — typically in the first week of the following month. You will receive an in-app notification as soon as your payslip is ready.',
          },
          {
            id: 'pp-2',
            question: 'How do I download my payslip?',
            answer: 'Go to Payroll → My Payslips. Find the month you need and click the "Download" button in the Action column. A print dialog will open where you can save the payslip as a PDF to your device.',
          },
          {
            id: 'pp-3',
            question: 'My payslip figures look incorrect. What should I do?',
            answer: 'First, verify your gross pay, deductions (TDS, PF, Other), and net pay on the payslip. If there is a discrepancy, contact your HR Manager directly with the specific figures in question. Do not make assumptions — salary errors must be resolved before the next payroll cycle.',
          },
          {
            id: 'pp-4',
            question: 'What deductions appear on my payslip?',
            answer: 'Standard deductions include Income Tax (TDS), Employee Provident Fund (EPF/PF), and any other applicable statutory or voluntary deductions. The exact breakdown is itemized on every payslip download.',
          },
        ],
      },
      {
        id: 'account-security',
        label: 'Account & Security',
        icon: 'Lock',
        items: [
          {
            id: 'as-1',
            question: 'How do I change my password?',
            answer: 'Go to Settings → Security and click "Change Password". Enter your current password, followed by your new password twice. Passwords must be at least 8 characters and include a mix of letters, numbers, and symbols.',
          },
          {
            id: 'as-2',
            question: 'What should I do if I suspect unauthorized access to my account?',
            answer: 'Change your password immediately via Settings → Security. Then contact your HR Administrator or IT support to report the incident. They can review access logs and revoke any active sessions on your behalf.',
          },
          {
            id: 'as-3',
            question: 'Is my payroll and personal data encrypted?',
            answer: 'Yes. All data in HRMSPro is encrypted in transit (TLS) and at rest. Payroll data is additionally access-controlled — employees can only view their own records, and HR Managers have scoped access based on their organizational permissions.',
          },
          {
            id: 'as-4',
            question: 'How do I log out securely?',
            answer: 'Click your avatar in the top-right navbar and select "Logout". This clears your session token from the browser. For shared or public devices, always log out explicitly and close the browser tab afterward.',
          },
        ],
      },
    ];
    
    const created = await FAQCategory.insertMany(seedData);
    res.status(200).json({ success: true, message: 'FAQs seeded successfully', categories: created });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to seed FAQs', error: error.message });
  }
};
